# Auto-label PRs based on changed files

"documentation":
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**/*"]

"tests":
  - changed-files:
      - any-glob-to-any-file: ["tests/**/*", "**/*_test.rs", "**/test_*.rs"]

"benchmarks":
  - changed-files:
      - any-glob-to-any-file: ["benches/**/*"]

"examples":
  - changed-files:
      - any-glob-to-any-file: ["examples/**/*"]

"dependencies":
  - changed-files:
      - any-glob-to-any-file: ["Cargo.toml", "Cargo.lock"]

"ci/cd":
  - changed-files:
      - any-glob-to-any-file: [".github/**/*"]

"core":
  - changed-files:
      - any-glob-to-any-file: ["src/signal/**/*", "src/runtime/**/*"]

"store":
  - changed-files:
      - any-glob-to-any-file: ["src/store/**/*"]
